#!/bin/sh
f="/home/ichigo/stuff/logs/filesys/$(date +%F_%T_log)"
/bin/tree -iaf -I 'mnt|.cache|hdd|discord|chromium|Steam|repos|nvim|.cargo|firefox|.git' /home/ichigo > "$f"
chown -f ichigo:ichigo "$f"
