#!/bin/bash

PLAYER="spotify"
ART_CACHE_DIR="$HOME/.cache/spotify_album_art"
ALBUMART_PNG="$ART_CACHE_DIR/$albumart_id.png"
mkdir -p "$ART_CACHE_DIR"

parse_op() {
    echo "$(echo "$op" | grep "$1" | awk '{for(i=3;i<=NF;i++){printf "%s ", $i}}' | xargs)"
}

playerctl -p "$PLAYER" metadata title -F | while read line;
do
    # very lame
    op=$(playerctl -p "$PLAYER" metadata)

    title=$(parse_op title)
    artist=$(parse_op artist)
    album=$(parse_op album[[:space:]])
    albumart_url=$(parse_op artUrl)
    albumart_id=$(echo "$albumart_url" | awk -F\/ '{print $NF}' | xargs) # xargs to trim whitespace


    if [ ! -f "$ALBUMART_PNG" ]; then
        curl $albumart_url --silent --output "$ALBUMART_PNG"
    fi

    if [ -n "$title" ]; then
        dunstify -t 3000 -r 412 -i "$ALBUMART_PNG" "$title" "$artist - $album"
    fi
done

