#! /bin/sh
bspc rule -r "*"

# startup
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
pgrep -x Discord > /dev/null || discord &
# pgrep -x transmission-daemon > /dev/null || transmission-daemon &
pgrep -x acpi_listen > /dev/null || $HOME/scripts/utils/pa_source_port &

bspc monitor -d I II III IV V VI VII VIII IX X

# general
bspc config border_width 1
bspc config window_gap 0
bspc config top_padding 30
bspc config focused_border_color \#449dab

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config automatic_scheme alternate

# application rules
bspc rule -a discord desktop='^9' follow=false
bspc rule -a Steam desktop='^8' state=floating follow=false
bspc rule -a chatterino follow=false split_ratio=0.83
bspc rule -a Zathura state=tiled
bspc rule -a tabbed:zt desktop='^3' follow=true
bspc rule -a Spotify desktop='^9' follow=false

# desktop rules
for desktop_id in $(bspc query -D); do
    bspc desktop $desktop_id --layout monocle
done
