#!/bin/bash
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh # keyring doesn't work without this
xsetroot -cursor_name left_ptr
xset r rate 200 70
dunst &
picom &
xwallpaper --zoom $HOME/pictures/wallpaper.png
xbacklight -set 70
exec bspwm
